export const RoomData = [
    {
        id: "cse-library",
        label: "CSE Dept. Library",
        x: 1043,
        y: 121,
        width: 152,
        height: 277,
        color: "blue",
    },
    {
        id: "TF-03",
        label: "Lecture Hall TF-03",
        x: 1044,
        y: 400,
        width: 150,
        height: 312,
        color: "red",
    },
    {
        id: "TF-04",
        label: "Lecture Hall TF-04",
        x: 1267,
        y: 526,
        width: 152,
        height: 274,
        color: "red",
    },
    {
        id: "cse-seminar",
        label: "CSE Seminar Hall",
        x: 1041,
        y: 801,
        width: 148,
        height: 364,
        color: "blue",
    },
    {
        id: "washrooms",
        label: "Ladies WC Left Wing",
        x: 52,
        y: 192,
        width: 150,
        height: 130,
        color: "green",
    },
    {
        id: "cyber-lab",
        label: "Cyber Security Lab 02",
        x: 51,
        y: 399,
        width: 224,
        height: 150,
        color: "blue",
    },
    {
        id: "TF-223",
        label: "Room TF-223",
        x: 49,
        y: 551,
        width: 227,
        height: 291,
        color: "red",
    },
    {
        id: "left-room-1",
        label: "Unlabeled Room 1",
        x: 47,
        y: 842,
        width: 230,
        height: 290,
    },
    {
        id: "left-room-2",
        label: "Unlabeled Room 2",
        x: 49,
        y: 1131,
        width: 226,
        height: 285,
    },
    {
        id: "left-room-3",
        label: "Unlabeled Room 3",
        x: 48,
        y: 1418,
        width: 154,
        height: 281,
    },
    {
        id: "hod-room",
        label: "AI/ML HOD Room",
        x: 276,
        y: 1499,
        width: 73,
        height: 108,
        color: "blue",
    },
    {
        id: "aiml-lab",
        label: "AI/ML Lab 02",
        x: 501,
        y: 1368,
        width: 197,
        height: 321,
        color: "blue",
    },
    {
        id: "TF-08",
        label: "Room TF-08",
        x: 695,
        y: 1366,
        width: 197,
        height: 324,
        color: "red",
    },
    {
        id: "einstein-hall",
        label: "Albert Einstein Hall",
        x: 49,
        y: 1820,
        width: 391,
        height: 321,
        color: "blue",
    },
    {
        id: "room-1766762689958",
        label: "Gents WC Right Wing",
        x: 1042,
        y: 29,
        width: 154,
        height: 92,
        color: "green",
    },
    {
        id: "room-1766770066648",
        label: "Gents WC Left Wing",
        x: 275,
        y: 191,
        width: 76,
        height: 130,
        color: "green",
    },
    {
        id: "room-1766770136579",
        label: "Staff WC Right Wing",
        x: 1269,
        y: 30,
        width: 153,
        height: 94,
        color: "green",
    },
];
